spring.application.name=jokenponline

server.port=8081
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgresPW
spring.datasource.url=jdbc:postgresql://localhost:5433/jokenponline?currentSchema=infra

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=infra

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.modulith.events.jdbc.schema=infra

spring.flyway.default-schema=infra
spring.flyway.schemas=infra,auth
spring.flyway.enabled=true

spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=heckvault

spring.config.import=vault://secret/jokenponline

security.variables.private-key=${security.jwt.private-key}
security.variables.public-key=${security.jwt.public-key}
security.variables.token-expiration-time-minutes = 60